name: Frontend - CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'saudacao-app/**'  

  pull_request:
    branches: [ "main" ]
    paths:
      - 'saudacao-app/**'  

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'
        cache-dependency-path: saudacao-app/package-lock.json

    - name: Restore dependencies
      run: npm ci
      working-directory: ./saudacao-app

    - name: Build
      run: npm run build
      working-directory: ./saudacao-app

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: frontend-publish-${{ github.ref_name }}
        path: saudacao-app/dist/browser
